apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: catalog
  selector:
    app: catalog
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: dtdemos/keptn-orders-catalog:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: catalog
        env:
        - name: DT_TAGS
          value: "application=orders service=catalog"  
