apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: order
  selector:
    app: order
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: dtdemos/keptn-orders-order:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: order
        env:
        - name: DT_TAGS
          value: "application=orders service=order"  
