--- 
apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  selector: 
    app: {{ .Values.service.name }}