--- 
apiVersion: v1
kind: Service
metadata: 
  name: order-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
  selector: 
    app: order-service
