---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  labels:  
    app:  loadgenerator
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: loadgenerator
  type: ClusterIP  
