---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytravel-www
  labels:
    app: easytravel
    type: www
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      easytravel-tier: easytravel-www
      app: easytravel
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        easytravel-tier: easytravel-www
        app: easytravel
        type: www-pod
        app.kubernetes.io/name: {{ .Values.keptn.service }}
        app.kubernetes.io/instance: "{{ .Values.keptn.service }}-{{ .Values.keptn.deployment }}"
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: "{{ .Values.keptn.project }}"
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/version: {{ (split ":" .Values.image)._1 | default "latest" }}        
    spec:
      containers:
      - env:
        - name: ET_FRONTEND_LOCATION
          value: "easytravel-frontend:8080"
        - name: ET_BACKEND_LOCATION
          value: "easytravel-backend:8080"  
        - name: DT_CUSTOM_PROP
          value: "version={{ .Chart.Version }} revision={{ .Release.Revision }} releasename={{ .Release.Name }} keptn_project={{ .Values.keptn.project }} keptn_service={{ .Values.keptn.service }} keptn_stage={{ .Values.keptn.stage }} keptn_deployment={{ .Values.keptn.deployment }}"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.labels['deployment']"
        - name: CONTAINER_IMAGE
          value: "{{ .Values.image }}"
        - name: KEPTN_PROJECT
          value: "{{ .Values.keptn.project }}"
        - name: KEPTN_STAGE
          value: "{{ .Values.keptn.stage }}"
        - name: KEPTN_SERVICE
          value: "{{ .Values.keptn.service }}"
        - name: KEPTN_DEPLOYMENT
          value: "{{ .Values.keptn.deployment }}"         
        image: dynatrace/easytravel-nginx
        imagePullPolicy: Always
        name: easytravel-www
        ports:
        - containerPort: 80
          protocol: TCP
