apiVersion: v1
kind: Service
metadata:
  name: easytravel-www
  labels:
    app: easytravel-www
spec:
  type: LoadBalancer
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
#      nodePort: 30080
  selector:
    app: easytravel-www
