---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-www
  labels:
    app: easytravel-www
spec:
  type: reverse-proxy
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: easytravel-www
  type: ClusterIP  
