apiVersion: v1
kind: Service
metadata:
  name: easytravel-www
  labels:
    app: easytravel-www
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: easytravel-www
