replicaCount: 1
image: docker.io/dt-orders-customer-service:1
service:
    name: customer-service
    externalPort: 80
    internalPort: 8080
container:
    name: customer-service
resources:
    limits:
        cpu: 100m
        memory: 128Mi
    requests:
        cpu: 100m
        memory: 128Mi  