---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-frontend
  labels:
    app: easytravel-frontend
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
#    nodePort: 30080
#  - name: http2
#    nodePort: 30280
#    port: 8280
#    protocol: TCP
#    targetPort: 8280
  selector:
    app: easytravel-frontend
#  sessionAffinity: None
  type: ClusterIP
