---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-frontend
  labels:
    app: easytravel-frontend
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: easytravel-frontend
  type: ClusterIP
