---
apiVersion: v1
kind: Service
metadata:
  name: easytravel-frontend
  labels:
    app: easytravel-frontend
spec:
  ports:
  - name: "port1"
#    nodePort: 30080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: "port2"
#    nodePort: 30280
    port: 8280
    protocol: TCP
    targetPort: 8280
  selector:
    app: easytravel-frontend
#  sessionAffinity: None
#  type: NodePort
